<div class="view">
<h1>Details of <?php echo $this->model->getUsername();?></h1>
<?php $url = $this->url(
		array('controller'=>'user', 'action'=>'edit', 'id' => $this->model->getId()),
		'default', true);?>
	<a href="<?php echo $url ?>
		">edit user</a>
<br />
<span class="realname">Name: <?php echo $this->model->getRealname();?></span><br />
<span class="role">Role: <?php echo $this->model->getRole();?></span><br />
<span class="phone_nr">Phone nr.: <?php echo $this->model->getPhoneNr();?></span><br />
<span class="location">Location: <?php echo $this->model->getLocation();?></span><br />
</div>