<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Aeolus Disaster Management System</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header">
    <div id="header-logo">
        <b>Aeolus Disaster Management System</b>
    </div>
    <div id="header-navigation">
        <a href="<?php echo $this->url(
            array('controller'=>'Incident', 'action'=>'add'),
            'default',
            true) ?>">Report Incident</a>
        <a href="<?php echo $this->url(
            array('controller'=>'Incident'),
            'default',
            true) ?>">List incidents</a>
    </div>
</div>
<?php echo $this->layout()->content ?>
 
</body>
</html>