<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Aeolus Disaster Management System</title>
  <?php echo $this->headLink()->appendStylesheet('/aeolus/public/css/global.css') ?>
  <?php echo $this->headScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false') ?>
  <?php echo $this->headScript()->appendFile('/aeolus/public/js/google_maps.js') ?>
</head>
<body onload="initialize(<?php print $this->jsInitParameters; ?>)">
    <div id="control">
		<div id="topleft"/><div id="header">
			<span class="bannertext">Queensland Disaster System</span>
		</div>
		<div id="midcontainer">
			<div id="left">
				<a href="<?php echo $this->url(
			            array('controller'=>'incident', 'action'=>'add'),
			            'default',
			            true) ?>">Report Incident</a>
			            <br />
			        <a href="<?php echo $this->url(
			            array('controller'=>'incident'),
			            'default',
			            true) ?>">List incidents</a>
			            <br />
			        <a href="<?php echo $this->url(
			            array('controller'=>'incident', 'action'=>'indexmap'),
			            'default',
			            true) ?>">Incident map</a>
			              <br />
			           <?php echo $this->loggedInAs(); ?> 
			</div>
			<div id="middle">
				<?php echo $this->layout()->content ?> 
			</div>			
			<div id="right">
			</div>
		</div>
	</div>
</body>
</html>