
<div class="view">
<h1>Details of <?php echo $this->model->getTitle();?></h1>
<?php $url = $this->url(
		array('controller'=>'incident', 'action'=>'edit', 'id' => $this->model->getId()),
		'default', true);?>
	<a href="<?php echo $url ?>
		">edit incident</a>
<?php $url = $this->url(
		array('controller'=>'incident', 'action'=>'assignpersonnel', 'id' => $this->model->getId()),
		'default', true);?>
	<a href="<?php echo $url ?>
		">assign personnel</a>
<br />
Public Description: <span class="details"><?php echo $this->model->getDescription();?></span><br />
Sensitive Description: <span class="sensitive_description"><?php echo $this->model->getSensitiveDescription();?></span><br />
<span>Verified: <?php echo ($this->model->getVerified()) ? 'yes' : 'no' ; ?></span>
<?php if(!$this->model->getVerified()):?>
	<?php $url = $this->url(
		array('controller'=>'incident', 'action'=>'verify', 'id' => $this->model->getId()),
		'default', true);?>
	<a href="<?php echo $url ?>
		">Verify incident</a>
<?php else :?>
	<?php $url = $this->url(
		array('controller'=>'incident', 'action'=>'unverify', 'id' => $this->model->getId()),
		'default', true);?>
	<a href="<?php echo $url ?>
		">Unverify incident</a>
<?php endif;?>
<?php if($this->model->getLatitude() && $this->model->getLongitude()) :?>
	<div id="map-label">Location </div>
	<div id="map_canvas"></div>
<?php endif;?>
</div>
